# Generated by Django 4.2.11 on 2024-03-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalbuddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='good_things',
        ),
    ]
