# Generated by Django 5.0.3 on 2024-03-23 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
    ]
