# Generated by Django 5.0.3 on 2024-03-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalbuddy', '0002_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='media',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
